---
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    dir: functions/process_incoming_image
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - process_incoming_image
      - --memory=256MB
      - --project=${PROJECT_ID}
      - --region=us-east4
      - --runtime=python39
      - --timeout=30
      - --trigger-event=google.storage.object.finalize
      - --trigger-resource=${_INCOMING_BUCKET}
      - -q
